/*
 * LoginUI.java
 *
 * Created on __DATE__, __TIME__
 */

package com.chat.ui;

import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.net.InetAddress;
import java.net.InetSocketAddress;
import java.net.Socket;
import java.net.UnknownHostException;
import java.util.ArrayList;

import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import com.chat.bean.UserBean;
import com.chat.client.ClientLogin;

/**
 *
 * @author  __USER__
 * 默认 服务器 端口 8005
 * 客户端                       8004
 */
public class LoginUI extends javax.swing.JFrame {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/** Creates new form LoginUI */
	private javax.swing.JLabel labelBackImage;
	private Socket socket=null;//socket 第一次在这个类建立的
	
	private String IP="127.0.0.1";//服务器 IP
	private String port="8005";//服务器端口
    private ArrayList<UserBean> listUser;
    
    private int localPort;
	public LoginUI() {
		
		initComponents();
		
		addListeners();
		
	}

	public void addListeners() {
		this.btLogin.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				btLoginActionPerformed();
			}
		});
		
		this.btRegister.addActionListener(new ActionListener(){
			public void actionPerformed(ActionEvent e) {
				btRegisterActionPerformed();
			}
			
		});
   
		this.btLogin.addKeyListener(new KeyAdapter() {
			public void keyPressed(KeyEvent e) {
				if(e.getKeyCode()==KeyEvent.VK_ENTER){
					btLoginActionPerformed();
				}
			}
		});	}
   
	@SuppressWarnings("unchecked")
	public void btLoginActionPerformed(){
		//登陆
		String userName = textUserName.getText();
		String pwd = new String(pwdPwd.getPassword());
		
		if(!(userName.equals("")||pwd.equals("")||userName==null||pwd==null)){
			
			if(IP!=null&&port!=null){
				try {			
				    socket = new Socket();
				   // socket.bind(new InetSocketAddress(8004));//绑定socket到本地端口8004
					socket.connect(new InetSocketAddress(InetAddress.getByName(IP),Integer.valueOf(port)),7000);
				} catch (NumberFormatException e1) {
					JOptionPane.showMessageDialog(null,"端口必须是数字");
				} catch (UnknownHostException e1) {
					JOptionPane.showMessageDialog(null,"UnKownHostException");
				} catch (IOException e1) {
					JOptionPane.showMessageDialog(null,"服务器没打开");
				}
			}
			
			if(socket.isConnected()&&!socket.isClosed()){
				ClientLogin login = new ClientLogin(userName, pwd, socket);
				Object list = login.login();//登陆
				if(list==null){
					;
					
				}
				else{
					//如果登陆成功,list转换,list 要包含 me,将list给MainClientUI
					listUser = (ArrayList<UserBean>)list;
					localPort = socket.getLocalPort();//这一行是为了 不固定客户端 的端口为8004
					try {
						socket.close();
					} catch (IOException e) {
						JOptionPane.showMessageDialog(null,"socket.close()");
					}
					java.awt.EventQueue.invokeLater(new Runnable() {
						public void run() {
							new MainClientUI(listUser, IP,port,localPort).setVisible(true);
						}
					});
					this.dispose();
					
				}
			}
			else{
				JOptionPane.showMessageDialog(null,"无法和服务器取得联系");
				String tmp=JOptionPane.showInputDialog("请输入服务器IP和端口号,以,隔开", "127.0.0.1,8005");
				if(tmp!=null&&tmp.contains(",")){
					String  tmps[] = tmp.split(",");
					IP  = tmps[0];
					port = tmps[1];	
					
				}
			}
		}
		else{
			JOptionPane.showMessageDialog(null,"用户名和密码不能为空");
		}
		
		if(socket!=null){
			try {
				socket.close();//关闭socket
			} catch (IOException e) {
				JOptionPane.showMessageDialog(null,"LoginUI——IOException");
			}
		}
		
	}
	public void btRegisterActionPerformed(){
		new RegisterUI(this,true).setVisible(true);
	}
	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		btRegister = new javax.swing.JButton();
		btLogin = new javax.swing.JButton();
		textUserName = new javax.swing.JTextField();
		pwdPwd = new javax.swing.JPasswordField();
 
		
		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("\u767b\u9646");
		setIconImage(new javax.swing.ImageIcon(
				"src\\com\\chat\\ui\\dog_left.png").getImage());
		setResizable(false);//取消最大化
		
		//居中显示
		int w = (Toolkit.getDefaultToolkit().getScreenSize().width) / 3;
		int h = (Toolkit.getDefaultToolkit().getScreenSize().height) / 3;
		setLocation(w, h);
		
		jLabel1.setFont(new java.awt.Font("新宋体-18030", 0, 12));
		jLabel1.setText("\u7528\u6237\u540d");

		jLabel2.setFont(new java.awt.Font("新宋体-18030", 0, 12));
		jLabel2.setText("\u5bc6  \u7801");

		btRegister.setFont(new java.awt.Font("新宋体-18030", 0, 12));
		btRegister.setText("\u6ce8\u518c");

		btLogin.setFont(new java.awt.Font("新宋体-18030", 0, 12));
		btLogin.setText("\u767b\u9646");
        
		labelBackImage = new JLabel();
		labelBackImage.setIcon(new ImageIcon("src\\com\\chat\\ui\\bg.jpg"));
		labelBackImage.add(this.btRegister);
		labelBackImage.add(this.btLogin);
		labelBackImage.add(this.jLabel1);
		labelBackImage.add(this.jLabel2);
		labelBackImage.add(this.pwdPwd);
		labelBackImage.add(this.textUserName);
		labelBackImage.setBounds(0,0,400,200);
		
		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout
				.setHorizontalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addGap(71, 71, 71)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addComponent(
																				btRegister)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																				90,
																				Short.MAX_VALUE)
																		.addComponent(
																				btLogin))
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addGroup(
																				layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.TRAILING)
																						.addComponent(
																								jLabel1,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								Short.MAX_VALUE)
																						.addComponent(
																								jLabel2,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								Short.MAX_VALUE))
																		.addGap(
																				27,
																				27,
																				27)
																		.addGroup(
																				layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING,
																								false)
																						.addComponent(
																								pwdPwd)
																						.addComponent(
																								textUserName,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								141,
																								Short.MAX_VALUE))))
										.addContainerGap(57, Short.MAX_VALUE)));
		layout
				.setVerticalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addGap(46, 46, 46)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																jLabel1,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE)
														.addComponent(
																textUserName))
										.addGap(32, 32, 32)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																jLabel2,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																18,
																Short.MAX_VALUE)
														.addComponent(
																pwdPwd,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(32, 32, 32)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																btRegister,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE)
														.addComponent(
																btLogin,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE))
										.addContainerGap()));
		
        getContentPane().add(labelBackImage);
		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new LoginUI().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton btRegister;
	private javax.swing.JButton btLogin;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JPasswordField pwdPwd;
	private javax.swing.JTextField textUserName;
	// End of variables declaration//GEN-END:variables

}